# 1 1. Write programs in Python using NumPy library to do the following:
a. Create a two dimensional array, ARR1 having random values from 0 to 1. Compute the mean, standard
deviation, and variance of ARR1 along the second axis.

### (a) Creating 2D array having random value b/w 0 and 1

In [6]:
import numpy as np
ARR1 = np.random.rand(3, 4)
ARR1

array([[0.11621835, 0.50905352, 0.14073355, 0.2343117 ],
       [0.61855582, 0.58831967, 0.84579414, 0.15839076],
       [0.28565362, 0.74708142, 0.41764573, 0.58080104]])

In [7]:
mean = np.mean(ARR1, axis=1)
mean

array([0.25007928, 0.5527651 , 0.50779545])

In [8]:
std_deviation = np.std(ARR1, axis=1)
std_deviation

array([0.15587777, 0.24849028, 0.1732495 ])

In [54]:
variance= np.var(ARR1, axis=1)
variance

array([0.02429788, 0.06174742, 0.03001539])

## (b)

In [ ]:
b. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of
the array and then reshape it into an n x m array, where n and m are user inputs given at the run time.


In [ ]:
m = int(input("Enter value of m "))
n = int(input("Enter value of n "))
array = np.random.randint(0,100, size=(m,n))
array

In [ ]:
array.shape

In [ ]:
type(array)

In [ ]:
array.dtype

In [ ]:
array2 = np.reshape(array, (n, m))
array2

####  c. Test whether the elements of a given 1D array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.

In [ ]:
arr = np.array([0, 1, 2, 0, 3, np.nan, 5, 0, np.nan])
arr

In [ ]:
zeroIndices = np.where(arr == 0)[0]
zeroIndices

In [ ]:
nonZeroIndices = np.where(arr != 0)[0]
nonZeroIndices

In [ ]:
nanIndices = np.where(np.isnan(arr))[0]
nanIndices

#### d. Create three random arrays of the same size: Array1, Array2 and Array3. Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1. Find Covariance and Correlation of Array1 with Array4 and Array5 respectively.


In [12]:
m = int(input("Enter value of m "))
n = int(input("Enter value of n "))
size = (m, n)
Array1 = np.random.rand(*size)
Array2 = np.random.rand(*size)
Array3 = np.random.rand(*size)


Enter value of m 3
Enter value of n 3


In [41]:
Array1

array([[0.87762145, 0.43176375, 0.08982691],
       [0.95500678, 0.47611467, 0.97789125],
       [0.63660885, 0.40996277, 0.48498366]])

In [42]:
Array2

array([[0.90176128, 0.0874256 , 0.15929262],
       [0.09854058, 0.71424605, 0.00392788],
       [0.76901137, 0.99630357, 0.63919124]])

In [43]:
Array3

array([[0.09610567, 0.25276187, 0.8259654 ],
       [0.23257302, 0.66201574, 0.694816  ],
       [0.50649621, 0.53180754, 0.48118259]])

In [44]:
Array4 = Array3 - Array2
Array4

array([[-0.8056556 ,  0.16533627,  0.66667278],
       [ 0.13403244, -0.05223031,  0.69088811],
       [-0.26251516, -0.46449604, -0.15800865]])

In [45]:
Array5 = 2 * Array1
Array5

array([[1.7552429 , 0.8635275 , 0.17965383],
       [1.91001356, 0.95222935, 1.95578249],
       [1.27321771, 0.81992554, 0.96996732]])

In [38]:
#  covariance between arr1 and arr4
covariance_Array1_Array4 = np.cov(Array1, Array4)[0, 1]
covariance_Array1_Array4

0.003985596933373359

#### flatten return a copy of the array collapsed into one dimension, for multi-dimensional array, calling flatten will reshape it into a one-dimensional array.

#### Without flattening, np.cov will calculate the covariance between variables across observations. With flattening, it treats all values as a single set and calculates the covariance accordingly.

In [47]:
#  covariance between arr1 and arr4
covariance_Array1_Array4 = np.cov(Array1.flatten(), Array4.flatten())[0, 1]
covariance_Array1_Array4

-0.022526039359041395

In [48]:
#  covariance between arr1 and arr4
covariance_Array1_Array5 = np.cov(Array1.flatten(), Array5.flatten())[0, 1]
covariance_Array1_Array5

0.17502826059706025

In [49]:
# Calculate the correlation coeff between arr1 and arr4
correlation_Array1_Array4 = np.corrcoef(Array1.flatten(), Array4.flatten())[0, 1]
correlation_Array1_Array4 

-0.15512095346776342

In [50]:
# Calculate the correlation coeff between arr1 and arr5
correlation_Array1_Array5 = np.corrcoef(Array1.flatten(), Array5.flatten())[0, 1]
correlation_Array1_Array5 

1.0

##### e  Create two random arrays of the same size 10: Array1, and Array2. Find the sum of the first half of both the arrays and product of the second half of both the arrays

In [51]:
Array1 = np.random.rand(10)
Array2 = np.random.rand(10)

# Print the orig arrays
print("Array1:", Array1)
print("Array2:", Array2)

# Cal sum of first half of both arrays ---->using slicing
first_half_Array1 = np.sum(Array1[:5])
first_half_Array2 = np.sum(Array2[:5])

# Cal product second half of both arrays 
second_half_Array1 = np.prod(Array1[5:])
second_half_Array2 = np.prod(Array2[5:])

# Print the results
print("\nSum of the first half of Array1:", first_half_Array1)
print("Sum of the first half of Array2:", first_half_Array2)
print("\nProduct of the second half of Array1:", second_half_Array1)
print("Product of the second half of Array2:", second_half_Array2)


Array1: [0.1947504  0.30319871 0.05794727 0.64410539 0.26241741 0.23672814
 0.30483312 0.73321948 0.32179995 0.64604381]
Array2: [0.76965958 0.00500796 0.25269946 0.13154089 0.83862289 0.08671546
 0.75770732 0.32060634 0.79759902 0.76963099]

Sum of the first half of Array1: 1.4624191918755431
Sum of the first half of Array2: 1.9975307748984497

Product of the second half of Array1: 0.011000032450809416
Product of the second half of Array2: 0.012931154371882459


#### f. Create an array with random values. Determine the size of the memory occupied by the array.

In [ ]:

# Create an array with random values
random_array = np.random.rand(5, 5)

# Det size of memory occupied by the array in bytes
memory_size = random_array.nbytes

# Print the size in bytes and kilobytes
print(f"Memory size of the array: {memory_size} bytes")


#### g Create a 2-dimensional array of size m x n having integer elements in the range (10,100). Write statements to swap any two rows, reverse a specified column and store updated array in another variable

In [61]:
import numpy as np

# Function to create a 2-dimensional array of size m x n with integer elements in the range (10, 100)
def create_array(m, n):
    return np.random.randint(10, 100, size=(m, n))

# Function to swap any two rows of the array
def swap_rows(arr, row1, row2):
    arr[row1], arr[row2] = arr[row2].copy(), arr[row1].copy()  #neccessary----> because lost of value in row result to use copy

# Function to reverse a specified column of the array
def reverse_column(arr, col):
    arr[:, col] = arr[::-1, col]

# Set the size of the array
m, n = 4, 5

# Create the 2-dimensional array
original_array = create_array(m, n)

# Print the original array
print("Original Array:")
print(original_array)

# Swap any two rows (e.g., row 0 and row 2)
swap_rows(original_array, 0, 2)
print("\nArray after swapping two rows:")
print(original_array)

# Reverse a specified column (e.g., column 1)
reverse_column(original_array, 1)
print("\nArray after reversing a specified column:")
print(original_array)

# Store the updated array in another variable
updated_array = original_array.copy()
print("\nUpdated Array:")
print(updated_array)


Original Array:
[[44 97 32 21 31]
 [74 55 77 76 54]
 [38 27 92 48 48]
 [89 48 75 81 19]]

Array after swapping two rows:
[[38 27 92 48 48]
 [74 55 77 76 54]
 [44 97 32 21 31]
 [89 48 75 81 19]]

Array after reversing a specified column:
[[38 48 92 48 48]
 [74 97 77 76 54]
 [44 55 32 21 31]
 [89 27 75 81 19]]

Updated Array:
[[38 48 92 48 48]
 [74 97 77 76 54]
 [44 55 32 21 31]
 [89 27 75 81 19]]
